language: ruby
cache: bundler
rvm:
- 2.1.2
bundler_args: "--without production"
addons:
  postgresql: "9.3"
env:
  matrix:
  - SECRET_KEY_BASE=1a2s3d DEVISE_SECRET_KEY=3f4g5h DEVISE_PEPPER=h678k7l
  global:
    secure: SPQMQwcPKzsRXaP3iPW9uPZkDZpEqLQVYWR+wcNi1DCGAOn2LloQuVoSZeklvVwTOCB7eIRnHgok8uNKjo1sV9Z/ZIJoMD6OxiU8rAxYlS0SuQ/UNWdtohrwwLViD/Zd1yLn4qyJ86LdzruUMJMTykBd+U97489G+/U1qKVOGt0=
script: bundle exec rspec
notifications:
  flowdock:
    secure: D6hsFJBddIl5uRJUAOijc5c4kFQCUvRfueeVNxnDVrSgLxc8Yo/JAYkT6lrWqrflw6YJJsmnwDJPtG5HjAznaihNyfGU2s/6YwfAmDWiICG7yguEm/xdkpUae59nb//g95FU0l3j9OLnqqv5cyHIkkNRn5YjSUyYoQ43qRv+ROU=
before_install:
- sudo apt-get install -y libtag1-dev
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- bin/rake db:migrate RAILS_ENV=test
