language: ruby
rvm:
  - 2.1.1
bundler_args: "--without production"
env: SECRET_KEY_BASE=1a2s3d DEVISE_SECRET_KEY=3f4g5h DEVISE_PEPPER=h678k7l
script: rspec
notifications:
  flowdock:
    secure: D6hsFJBddIl5uRJUAOijc5c4kFQCUvRfueeVNxnDVrSgLxc8Yo/JAYkT6lrWqrflw6YJJsmnwDJPtG5HjAznaihNyfGU2s/6YwfAmDWiICG7yguEm/xdkpUae59nb//g95FU0l3j9OLnqqv5cyHIkkNRn5YjSUyYoQ43qRv+ROU=
before_install:
  - "sudo apt-get install -y libtag1-dev"
